### PR TITLE
add babel 6 default export support

### PR DESCRIPTION
**Pull request by jasisk**
This allows folks to use es6 transpiled by babel 6 for the controllers

/cc @totherik

### CODE REVIEW

**Comment by aredridel** [comment]
More babel than es6 but ++

**Comment by jasisk** [comment]
100%. Called out in the description. Will edit the title.

**Comment by grawk** [comment]
looking good. did you want a plus one from Erik? :+1: here

**Comment by jasisk** [comment]
Nope. Word on the street is that guy hates thumbs.

**Comment by tlivings** [comment]
:+1:

**Pull request closed without merging**
